name: Deploy SDK 
on:
  push:
    branches: [main, beta, alpha]

jobs:
  deploy-sdk:
    name: Deploy SDK with tag
    runs-on: ubuntu-latest
    steps:
      # To make git commits made by semantic-release be made to our bot and not "github-actions" user which doesn't trigger other Action Workflows. 
      # https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      
      # Perform git related tasks inside of semantic-release because `git config user...` is already setup. It's easier to run commands in there with exec plugin.
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 18
          extra_plugins: |
            @semantic-release/commit-analyzer@8
            @semantic-release/release-notes-generator@9
            @semantic-release/changelog@5
            @semantic-release/git@9
            @semantic-release/github@7
            @semantic-release/exec@5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}