name: Promote a release

on: 
  workflow_dispatch: # manually run this Action so you decide when deployments happen

jobs:
  promote-release:
    name: Promote a branch to the next release 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Prepare to promote 
        run: |
          git config user.email "frontend@customer.io"
          git config user.name "Ami CI"
      - name: Promote release 
        uses: levibostian/action-promote-semantic-release@v1
        with:
          sequence: "develop,alpha,beta,main"
          githubToken: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}